# Generated by Django 3.2 on 2024-10-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
