# Generated by Django 3.2 on 2024-10-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (1, '1'), (3, '3'), (5, '5'), (0, '0')]),
        ),
    ]
