# Generated by Django 3.2 on 2024-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20241024_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (2, '2'), (5, '5'), (1, '1'), (0, '0')]),
        ),
    ]
