# Generated by Django 3.2 on 2024-10-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (4, '4'), (5, '5'), (3, '3'), (1, '1'), (2, '2')]),
        ),
    ]
